name: untitled
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

dependencies:
  intl: ^0.19.0
  http: 1.1.2
  json_annotation: ^4.8.1
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0

